name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage flake8 black selenium

      # Run migrations
      - name: Run migrations
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
        run: |
          python manage.py migrate

      # Run unit and integration tests
      - name: Run Unit and Integration Tests
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
        run: |
          coverage run --source='.' manage.py test
          coverage report

      # Run E2E tests
      - name: Run E2E Tests
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
        run: |
          python -m unittest discover -s todo/tests/e2e

      # Run Flake8 linting
      - name: Run Flake8
        run: |
          flake8 .

      # Run Black linting
      - name: Run Black
        run: |
          black --check .
